name: Build Action
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: NPM Install
              run: npm ci
            - name: Commit data
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add -A node_modules
                git commit -m "Update release"
            - name: Push Changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: main
